services:
  - type: web
    name: notify-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/project/src/.render/chrome/opt/google/chrome/chrome
    buildpacks:
      - https://github.com/render-packages/puppeteer
      - render:node
